version: '3.8'

services:
  app:
    build: .
    restart: always
    container_name: reaction_app
    volumes:
      - ./users.db:/app/users.db

  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    container_name: nginx_proxy
    ports:
      # Expose both HTTP and HTTPS ports
      - "80:80"
      - "443:443"
    volumes:
      # Mount the nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount the landing page files
      - ./landing:/usr/share/nginx/html/landing:ro
      # Mount the SSL certificates from Certbot into the container
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app