version: '3.8'

services:
  # This is our main Streamlit application service
  app:
    build: .
    restart: always
    container_name: reaction_app
    volumes:
      # We mount the users.db file into the container.
      # This ensures our user data persists even if the container is rebuilt.
      # Docker will create the users.db file on the host if it doesn't exist.
      - ./users.db:/app/users.db
    # No command is needed here, as it's specified in the Dockerfile's CMD

  # This is the Nginx reverse proxy service
  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    container_name: nginx_proxy
    ports:
      - "80:80"  # Map port 80 on the droplet to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount our custom config file
    depends_on:
      - app # Nginx won't start until the 'app' service is ready