version: '3.8'

services:
  app:
    build: .
    restart: always
    container_name: reaction_app
    volumes:
      - ./users.db:/app/users.db

  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # This line is for the nginx configuration file (unchanged)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # --- ADD THIS LINE ---
      # This mounts your new landing page files into the Nginx container
      - ./landing:/usr/share/nginx/html/landing:ro
    depends_on:
      - app