          script: |
            # Navigate into the project directory
            cd ~/ReactionPredictor
            
            # Pull the latest code from your GitHub repository
            git pull origin main
            
            echo "✅ Latest code pulled. Forcing a clean rebuild of services..."
            
            # Stop and remove the old running containers to ensure a clean start
            docker-compose down
            
            # Rebuild the app image from scratch, ignoring any cache
            docker-compose build --no-cache app
            
            # Start the new services in detached mode
            docker-compose up -d
            
            # Clean up old, unused Docker images to save disk space
            docker image prune -af
            
            echo "🚀 Deployment successful!"