# Name of the workflow
name: Deploy to DigitalOcean via Password SSH

# Run this workflow on a push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Use a pre-built action for SSH deployment
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          # Get the droplet credentials from GitHub Secrets
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          # The script block contains the commands to run on your server
          script: |
            # Navigate into the project directory
            cd ~/ReactionPredictor
            
            # Pull the latest code from your GitHub repository
            git pull origin main
            
            echo "✅ Latest code pulled. Building and restarting services..."
            
            # Use Docker Compose to build the new image and restart the services
            docker-compose up --build -d
            
            # Clean up old, unused Docker images to save disk space
            docker image prune -af
            
            echo "🚀 Deployment successful!"